recipe: default.v1
assistant_id: 20250925-105644-amortized-mole
language: en

pipeline:
  # ============================================
  # STANDARD RASA NLU PIPELINE (NO OLLAMA)
  # ============================================
  - name: WhitespaceTokenizer
  
  - name: RegexFeaturizer
  
  - name: LexicalSyntacticFeaturizer
  
  - name: CountVectorsFeaturizer
  
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  
  # DIET handles intent classification + entity extraction
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  
  - name: EntitySynonymMapper
  
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 3
  
  - name: RulePolicy
    core_fallback_threshold: 0.1
    core_fallback_action_name: "action_default_fallback"
  
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 50
  
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true